import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { QueryClientProvider } from "@/app/queryClient";
import { Toaster } from "react-hot-toast";
import Providers from "@/utils/Providers";

const plus_jakarta = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={plus_jakarta.className}>
        <Providers>
          <QueryClientProvider>
            {children}
          </QueryClientProvider>
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
